version: 0.0
os: linux
files:
  # 서버의 destination 에  source 파일 배포
  - source:  /
    destination: /home/ec2-user/plz/
    overwrite: yes
    runas: ec2-user

permissions:
  - object: /home/ec2-user/plz/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # 배포 후 실행될 스크립트(start.sh)
  ApplicationStart:
    - location: ./scripts/start.sh
